/* Generated by scripts/migrate_tools.py. Cache public site resources only. */
const CACHE = "hoztools-root-432126261a8ad448";
const OFFLINE = '/offline.html';
const CORE = ["/offline.html", "/", "/ar/", "/es/", "/manifest.webmanifest", "/assets/app-icon-classic-clear-192.png", "/assets/core.js", "/assets/fonts/OFL.txt", "/assets/fonts/arabic-bold.ttf", "/assets/fonts/arabic-bold.woff2", "/assets/fonts/arabic-regular.ttf", "/assets/fonts/arabic-regular.woff2", "/assets/fonts/latin-bold.ttf", "/assets/fonts/latin-bold.woff2", "/assets/fonts/latin-regular.ttf", "/assets/fonts/latin-regular.woff2", "/assets/icons.js", "/assets/install-prompt.js", "/assets/logo-dark.svg", "/assets/logo-light.svg", "/assets/logo.svg", "/assets/soft-refinements.css", "/assets/soft-refinements.js", "/assets/soft-runtime.js", "/assets/soft-system.css", "/assets/tools-ui.css"];
const PAGES = new Set(["/", "/ar/", "/ar/calculators/", "/ar/image/", "/ar/password/", "/ar/pdf/", "/ar/qr/", "/ar/split-bill/", "/ar/text/", "/ar/whatsapp/", "/calculators/", "/es/", "/es/calculators/", "/es/image/", "/es/password/", "/es/pdf/", "/es/qr/", "/es/split-bill/", "/es/text/", "/es/whatsapp/", "/image/", "/password/", "/pdf/", "/qr/", "/split-bill/", "/text/", "/whatsapp/"]);
self.addEventListener('install', event => event.waitUntil((async () => {
  const cache = await caches.open(CACHE);
  await cache.addAll(CORE);
  await self.skipWaiting();
})()));
self.addEventListener('activate', event => event.waitUntil((async () => {
  const names = await caches.keys();
  await Promise.all(names.filter(n => n.startsWith('hoztools-') && n !== CACHE).map(n => caches.delete(n)));
  await self.clients.claim();
})()));
self.addEventListener('fetch', event => {
  const request = event.request, url = new URL(request.url);
  if (request.method !== 'GET' || url.origin !== self.location.origin) return;
  const path = url.pathname.replace(/index\.html$/, '');
  const page = request.mode === 'navigate' && (PAGES.has(path) || PAGES.has(path + '/'));
  const asset = url.pathname.startsWith('/assets/') && /\.(?:js|mjs|css|png|svg|jpg|jpeg|webp|ttf|woff2?|wasm|bcmap|icc|pfb)$/.test(url.pathname);
  const manifest = /^(?:\/(?:ar|es))?\/manifest\.webmanifest$/.test(url.pathname);
  if (!page && !asset && !manifest) return;
  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    try {
      const response = await fetch(request);
      if (response.ok && (response.type === 'basic' || response.type === 'default')) {
        event.waitUntil(cache.put(request, response.clone()).catch(() => {}));
      }
      return response;
    } catch {
      const cached = await cache.match(request);
      if (cached) return cached;
      // Precached shell entries have no query string.
      if (asset) {
        const shell = await cache.match(url.pathname);
        if (shell) return shell;
      }
      if (page) return (await cache.match(OFFLINE)) || Response.error();
      return Response.error();
    }
  })());
});
